version: '3'

services:
  mongo:
    container_name: jokes-mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=jokes-db
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
